services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: e-commercedb
    ports: ["5433:5432"]
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
